# Dependencies
# markdown:         redcarpet
# highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            'Real Geeks Website Designer'
tagline:          'Boost Your Sales on RealGeeks'
description:      '<a href="/about">Rauof</a> is a software engineer, you can hire him for your web project, ask him, or say hi by <a href="mailto:abdelrauof97@gmail.com">Email</a>, or follow him on <a href="https://www.linkedin.com/in/abdelrauof/">LinkedIn</a>'
url:              http://rauof.com
baseurl:          /

author:
  name:           'Abdelrauof Mohammed'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/abdelrauof97
twitter:            https://twitter.com/AbdelrauofM
